In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

#daily-total-female-births

In [2]:
f_birth=pd.read_csv(r'C:\Users\ELCOT\Documents\Machine learning\Datasets\daily-total-female-births.csv',index_col=[0],parse_dates=[0])

In [3]:
f_birth.head()

Births
Date              
1959-01-01      35
1959-01-02      32
1959-01-03      30
1959-01-04      31
1959-01-05      44

In [4]:
f_birth.tail()

Births
Date              
1959-12-27      37
1959-12-28      52
1959-12-29      48
1959-12-30      55
1959-12-31      50

In [5]:
#normalization

#1.if data on different scales(m,cm like that)
#2.linear and logistic regreesion algorithm fine

#normalization=(x-min)/(max-min)

In [6]:
f_birth.min()

Births    23
dtype: int64

In [7]:
f_birth.max()

Births    73
dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
birth_arr=f_birth.values

In [10]:
birth_arr

array([[35],
       [32],
       [30],
       [31],
       [44],
       [29],
       [45],
       [43],
       [38],
       [27],
       [38],
       [33],
       [55],
       [47],
       [45],
       [37],
       [50],
       [43],
       [41],
       [52],
       [34],
       [53],
       [39],
       [32],
       [37],
       [43],
       [39],
       [35],
       [44],
       [38],
       [24],
       [23],
       [31],
       [44],
       [38],
       [50],
       [38],
       [51],
       [31],
       [31],
       [51],
       [36],
       [45],
       [51],
       [34],
       [52],
       [47],
       [45],
       [46],
       [39],
       [48],
       [37],
       [35],
       [52],
       [42],
       [45],
       [39],
       [37],
       [30],
       [35],
       [28],
       [45],
       [34],
       [36],
       [50],
       [44],
       [39],
       [32],
       [39],
       [45],
       [43],
       [39],
       [31],
       [27],
       [30],
       [42],
       [46],

In [11]:
scaler=MinMaxScaler(feature_range=(0,1))

In [12]:
scaler=scaler.fit(birth_arr)

In [13]:
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [14]:
scaler.data_min_

array([23.])

In [15]:
scaler.data_max_

array([73.])

In [16]:
birth_normalize=scaler.transform(birth_arr)

In [17]:
birth_normalize

array([[0.24],
       [0.18],
       [0.14],
       [0.16],
       [0.42],
       [0.12],
       [0.44],
       [0.4 ],
       [0.3 ],
       [0.08],
       [0.3 ],
       [0.2 ],
       [0.64],
       [0.48],
       [0.44],
       [0.28],
       [0.54],
       [0.4 ],
       [0.36],
       [0.58],
       [0.22],
       [0.6 ],
       [0.32],
       [0.18],
       [0.28],
       [0.4 ],
       [0.32],
       [0.24],
       [0.42],
       [0.3 ],
       [0.02],
       [0.  ],
       [0.16],
       [0.42],
       [0.3 ],
       [0.54],
       [0.3 ],
       [0.56],
       [0.16],
       [0.16],
       [0.56],
       [0.26],
       [0.44],
       [0.56],
       [0.22],
       [0.58],
       [0.48],
       [0.44],
       [0.46],
       [0.32],
       [0.5 ],
       [0.28],
       [0.24],
       [0.58],
       [0.38],
       [0.44],
       [0.32],
       [0.28],
       [0.14],
       [0.24],
       [0.1 ],
       [0.44],
       [0.22],
       [0.26],
       [0.54],
       [0.42],
       [0.

In [18]:
for i in range(5):
    print(birth_normalize[i])

[0.24]
[0.18]
[0.14]
[0.16]
[0.42]


In [19]:
#dividing the data in to train & test

birth_train=birth_normalize[0:330]
birth_test=birth_normalize[330:365]

In [20]:
birth_train.size

330

In [21]:
birth_test.size

35

In [22]:
from statsmodels.tsa.arima_model import ARIMA


In [23]:
birth_model=ARIMA(birth_train,order=(2,1,3))

In [24]:
birth_model_fit=birth_model.fit()

In [25]:
birth_model_fit.aic

-343.1628944652838

In [26]:
#forecasting
birth_forecast=birth_model_fit.forecast(steps=35)[0]

In [27]:
birth_forecast

array([0.44607595, 0.46621699, 0.41298882, 0.43184464, 0.46994569,
       0.42687067, 0.42179678, 0.46688205, 0.44150949, 0.4176209 ,
       0.45904604, 0.45391895, 0.41947975, 0.44913696, 0.46207963,
       0.42622792, 0.43984807, 0.465208  , 0.43587126, 0.43329575,
       0.46371845, 0.44613059, 0.43066558, 0.45893734, 0.45497267,
       0.43211441, 0.45267059, 0.46100126, 0.43690717, 0.44674106,
       0.46364823, 0.44372031, 0.44259867, 0.46315735, 0.45102014])

In [28]:
from  sklearn.metrics import mean_squared_error
mean_squared_error(birth_test,birth_forecast)

0.01882391448924226

In [29]:
birth_forecast_reshape=birth_forecast.reshape(len(birth_forecast),1)
birth_forecast_reverse=scaler.inverse_transform(birth_forecast_reshape)

In [30]:
birth_forecast_reverse

array([[45.30379735],
       [46.31084957],
       [43.64944124],
       [44.59223186],
       [46.49728453],
       [44.34353326],
       [44.08983878],
       [46.34410264],
       [45.07547465],
       [43.88104508],
       [45.95230208],
       [45.6959474 ],
       [43.97398759],
       [45.45684805],
       [46.10398137],
       [44.31139589],
       [44.99240331],
       [46.26039977],
       [44.79356311],
       [44.66478771],
       [46.18592261],
       [45.30652955],
       [44.53327898],
       [45.94686688],
       [45.74863357],
       [44.60572055],
       [45.63352961],
       [46.05006281],
       [44.84535828],
       [45.33705292],
       [46.18241161],
       [45.1860156 ],
       [45.12993374],
       [46.15786748],
       [45.55100699]])

In [31]:
birth_test_reshape=birth_test.reshape(len(birth_test),1)
birth_test_reverse=scaler.inverse_transform(birth_test_reshape)

In [32]:
np.sqrt(mean_squared_error(birth_test_reverse,birth_forecast_reverse))

6.860013573099229

In [35]:
#Standardization

from sklearn.preprocessing import StandardScaler

In [37]:
std_scaler=StandardScaler()
std_scaler=std_scaler.fit(birth_arr)

In [39]:
std_scaler.mean_

array([41.98082192])

In [40]:
std_scaler.var_

array([53.84894727])

In [41]:
std_birth=std_scaler.transform(birth_arr)

In [42]:
for i in range(5):
    print(std_birth[i])

[-0.95130099]
[-1.36012148]
[-1.63266846]
[-1.49639497]
[0.27516045]


In [43]:
std_birth_train=std_birth[0:330]
std_birth_test=std_birth[330:365]

In [46]:
std_birth_arima=ARIMA(std_birth_train,order=(2,1,3))

In [47]:
std_birth_arima_fit=std_birth_arima.fit()

In [48]:
std_birth_arima_fit.aic

919.4940817063124

In [51]:
std_birth_forecast=std_birth_arima_fit.forecast(steps=35)[0]

In [52]:
std_birth_forecast

array([0.45281292, 0.59005091, 0.2273733 , 0.35584603, 0.61545494,
       0.32195801, 0.2873835 , 0.59457915, 0.42170029, 0.25893013,
       0.54118659, 0.50625257, 0.27159473, 0.47366899, 0.56185558,
       0.3175731 , 0.41037691, 0.58317058, 0.3832782 , 0.36573057,
       0.57302095, 0.45318068, 0.34780793, 0.54044363, 0.51342694,
       0.35767804, 0.49774341, 0.55450342, 0.39033258, 0.45734036,
       0.572539  , 0.4367537 , 0.42911388, 0.56919424, 0.48649142])

In [53]:
std_birth_test

array([[ 1.22907491],
       [ 0.54770744],
       [ 0.27516045],
       [ 1.3653484 ],
       [ 0.41143395],
       [-1.36012148],
       [ 0.54770744],
       [-0.13366003],
       [-1.08757449],
       [-1.22384798],
       [-0.8150275 ],
       [ 0.95652792],
       [ 0.13888696],
       [ 0.13888696],
       [-1.08757449],
       [-0.40620702],
       [-0.95130099],
       [ 1.3653484 ],
       [ 0.68398093],
       [ 1.3653484 ],
       [-0.40620702],
       [-0.26993352],
       [ 0.00261346],
       [ 0.00261346],
       [ 1.5016219 ],
       [-0.40620702],
       [-0.26993352],
       [-0.54248051],
       [ 0.27516045],
       [-1.08757449],
       [-0.67875401],
       [ 1.3653484 ],
       [ 0.82025443],
       [ 1.77416889],
       [ 1.09280142]])

In [55]:
birth_forecast_reshape=std_birth_forecast.reshape(len(std_birth_forecast),1)

In [56]:
std_birth_forecast_rev = std_scaler.inverse_transform(birth_forecast_reshape)

In [57]:
std_birth_forecast_rev

array([[45.3036465 ],
       [46.31072419],
       [43.64932909],
       [44.59208565],
       [46.49714366],
       [44.34340912],
       [44.089695  ],
       [46.34395324],
       [45.07533636],
       [43.88089893],
       [45.9521488 ],
       [45.69579654],
       [43.97383409],
       [45.4566922 ],
       [46.10382166],
       [44.31123184],
       [44.99224327],
       [46.26023503],
       [44.79338797],
       [44.66462018],
       [46.18575519],
       [45.30634521],
       [44.53310057],
       [45.9466968 ],
       [45.74844339],
       [44.60552927],
       [45.63335471],
       [46.04987014],
       [44.84515425],
       [45.33686969],
       [46.18221854],
       [45.18580105],
       [45.12973861],
       [46.15767407],
       [45.55078554]])

In [59]:
birth_test_reshape=std_birth_test.reshape(len(std_birth_test),1)
birth_test_rev=std_scaler.inverse_transform(birth_test_reshape)

In [60]:
birth_test_rev

array([[51.],
       [46.],
       [44.],
       [52.],
       [45.],
       [32.],
       [46.],
       [41.],
       [34.],
       [33.],
       [36.],
       [49.],
       [43.],
       [43.],
       [34.],
       [39.],
       [35.],
       [52.],
       [47.],
       [52.],
       [39.],
       [40.],
       [42.],
       [42.],
       [53.],
       [39.],
       [40.],
       [38.],
       [44.],
       [34.],
       [37.],
       [52.],
       [48.],
       [55.],
       [50.]])

In [61]:
np.sqrt(mean_squared_error(birth_test_rev,birth_forecast_reverse))

6.860013573099229